version: '3.9'

services:
  recipe-gpt:
    container_name: recipe-generator
    build:
      dockerfile: Dockerfile
      context: .
    image: recipe-gpt:latest
    environment:
      - NODE_ENV=production
      - ENV_FILE=.env
    ports:
      - "3010:3000"