version: '3.9'

services:
  chefcook-gpt:
    container_name: chefcook
    build:
      dockerfile: Dockerfile
      context: .
    image: chefcook-gpt:latest
    environment:
      - NODE_ENV=production
      - ENV_FILE=.env
    ports:
      - "3010:3000"
