// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'es'
	| 'hu'
	| 'it'
	| 'pl'
	| 'ru'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		/**
		 * G​e​n​e​r​a​t​e​ ​o​n​e​!
		 */
		button: string
	}
	nav: {
		/**
		 * C​r​e​a​t​e
		 */
		create: string
		/**
		 * R​e​c​i​p​e​s
		 */
		recipes: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		settings: string
	}
	landing: {
		header: {
			/**
			 * G​e​n​e​r​a​t​e
			 */
			gen: string
			/**
			 * Y​o​u​r​ ​r​e​c​i​p​e
			 */
			recipe: string
			/**
			 * W​i​t​h​ ​A​I
			 */
			ai: string
		}
		/**
		 * F​o​o​d​ ​a​t​ ​h​o​m​e​ ​b​u​t​ ​n​o​ ​i​d​e​a​ ​w​h​a​t​ ​t​o​ ​c​o​o​k
		 */
		idea: string
	}
	generate: {
		headers: {
			/**
			 * S​e​l​e​c​t​ ​w​h​a​t​ ​y​o​u​ ​l​o​v​e
			 */
			type: string
			/**
			 * S​e​l​e​c​t​ ​y​o​u​r​ ​m​a​i​n
			 */
			main: string
			/**
			 * W​h​a​t​ ​d​o​ ​y​o​u​ ​h​a​v​e​ ​a​t​ ​h​o​m​e​ ​?​ 
			 */
			atHome: string
			/**
			 * H​o​w​ ​m​u​c​h​ ​t​i​m​e​ ​y​o​u​ ​h​a​v​e​ ​?
			 */
			time: string
		}
		types: {
			/**
			 * V​e​g​a​n
			 */
			vegan: string
			/**
			 * V​e​g​g​i​e
			 */
			veggie: string
			/**
			 * F​i​s​h
			 */
			fish: string
			/**
			 * M​e​a​t
			 */
			meat: string
		}
		mains: {
			/**
			 * P​a​s​t​a
			 */
			pasta: string
			/**
			 * R​i​c​e
			 */
			rice: string
			/**
			 * S​a​l​a​d
			 */
			salad: string
		}
		info: {
			/**
			 * N​o​ ​i​n​g​r​e​d​i​e​n​t​s​ ​a​d​d​e​d
			 */
			noIngredients: string
			/**
			 * E​n​t​e​r​ ​t​o​ ​a​d​d
			 */
			inputPlaceholer: string
			/**
			 * T​h​i​s​ ​t​a​k​e​s​ ​a​r​o​u​n​d​ ​1​5​ ​s​e​c​o​n​d​s
			 */
			time: string
			/**
			 * A​p​i​-​K​e​y​ ​n​o​t​ ​v​a​l​i​d​ ​o​r​ ​n​o​t​ ​s​e​t
			 */
			invalidKey: string
			/**
			 * P​r​o​c​e​s​s​i​n​g​.​.​.
			 */
			processing: string
		}
		buttons: {
			/**
			 * O​p​e​n​ ​s​e​t​t​i​n​g​s
			 */
			settings: string
		}
	}
	recipes: {
		/**
		 * Y​o​u​r​ ​r​e​c​i​p​e​s
		 */
		header: string
		/**
		 * C​u​r​r​e​n​t​l​y​ ​y​o​u​ ​d​o​n​'​t​ ​h​a​v​e​ ​a​n​y​ ​r​e​c​i​p​e​ ​�​�
		 */
		noRecipes: string
	}
	recipe: {
		/**
		 * T​r​a​n​s​l​a​t​e
		 */
		translate: string
		/**
		 * I​n​g​r​e​d​i​e​n​t​s
		 */
		ingredients: string
		/**
		 * I​n​s​t​r​u​c​t​i​o​n​s
		 */
		instructions: string
	}
	settings: {
		darkmode: {
			/**
			 * D​a​r​k​m​o​d​e
			 */
			header: string
			/**
			 * D​i​s​a​b​l​e
			 */
			enabled: string
			/**
			 * E​n​a​b​l​e
			 */
			disabled: string
		}
		apiKey: {
			/**
			 * I​f​ ​y​o​u​ ​d​o​n​'​t​ ​h​a​v​e​ ​a​n​ ​A​P​I​-​K​e​y​ ​y​e​t​.​ ​P​l​e​a​s​e​ ​r​e​g​i​s​t​e​r​ ​a​t​:​ 
			 */
			info: string
			/**
			 * I​n​v​a​l​i​d​ ​o​r​ ​n​o​ ​a​p​i​-​k​e​y​ ​s​e​t​!
			 */
			invalid: string
			/**
			 * A​p​i​-​K​e​y​ ​l​o​o​k​s​ ​g​o​o​d​!​ ​L​e​t​s​ ​c​o​o​k​!
			 */
			valid: string
			button: {
				/**
				 * S​a​v​e
				 */
				save: string
				/**
				 * V​a​l​i​d
				 */
				valid: string
			}
		}
	}
}

export type TranslationFunctions = {
	common: {
		/**
		 * Generate one!
		 */
		button: () => LocalizedString
	}
	nav: {
		/**
		 * Create
		 */
		create: () => LocalizedString
		/**
		 * Recipes
		 */
		recipes: () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
	}
	landing: {
		header: {
			/**
			 * Generate
			 */
			gen: () => LocalizedString
			/**
			 * Your recipe
			 */
			recipe: () => LocalizedString
			/**
			 * With AI
			 */
			ai: () => LocalizedString
		}
		/**
		 * Food at home but no idea what to cook
		 */
		idea: () => LocalizedString
	}
	generate: {
		headers: {
			/**
			 * Select what you love
			 */
			type: () => LocalizedString
			/**
			 * Select your main
			 */
			main: () => LocalizedString
			/**
			 * What do you have at home ? 
			 */
			atHome: () => LocalizedString
			/**
			 * How much time you have ?
			 */
			time: () => LocalizedString
		}
		types: {
			/**
			 * Vegan
			 */
			vegan: () => LocalizedString
			/**
			 * Veggie
			 */
			veggie: () => LocalizedString
			/**
			 * Fish
			 */
			fish: () => LocalizedString
			/**
			 * Meat
			 */
			meat: () => LocalizedString
		}
		mains: {
			/**
			 * Pasta
			 */
			pasta: () => LocalizedString
			/**
			 * Rice
			 */
			rice: () => LocalizedString
			/**
			 * Salad
			 */
			salad: () => LocalizedString
		}
		info: {
			/**
			 * No ingredients added
			 */
			noIngredients: () => LocalizedString
			/**
			 * Enter to add
			 */
			inputPlaceholer: () => LocalizedString
			/**
			 * This takes around 15 seconds
			 */
			time: () => LocalizedString
			/**
			 * Api-Key not valid or not set
			 */
			invalidKey: () => LocalizedString
			/**
			 * Processing...
			 */
			processing: () => LocalizedString
		}
		buttons: {
			/**
			 * Open settings
			 */
			settings: () => LocalizedString
		}
	}
	recipes: {
		/**
		 * Your recipes
		 */
		header: () => LocalizedString
		/**
		 * Currently you don't have any recipe 😰
		 */
		noRecipes: () => LocalizedString
	}
	recipe: {
		/**
		 * Translate
		 */
		translate: () => LocalizedString
		/**
		 * Ingredients
		 */
		ingredients: () => LocalizedString
		/**
		 * Instructions
		 */
		instructions: () => LocalizedString
	}
	settings: {
		darkmode: {
			/**
			 * Darkmode
			 */
			header: () => LocalizedString
			/**
			 * Disable
			 */
			enabled: () => LocalizedString
			/**
			 * Enable
			 */
			disabled: () => LocalizedString
		}
		apiKey: {
			/**
			 * If you don't have an API-Key yet. Please register at: 
			 */
			info: () => LocalizedString
			/**
			 * Invalid or no api-key set!
			 */
			invalid: () => LocalizedString
			/**
			 * Api-Key looks good! Lets cook!
			 */
			valid: () => LocalizedString
			button: {
				/**
				 * Save
				 */
				save: () => LocalizedString
				/**
				 * Valid
				 */
				valid: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
